---
name: ServerList
version: 1.0.0
main: Kelvinlolz\ServerList\Main
api: 4.0.0
src-namespace-prefix: Kelvinlolz\ServerList

commands:
  servers:
    description: Display server list
    usage: "/servers"
    permission: servers.list

permissions:
  servers.list:
    default: true
  servers.reload:
    default: op
...
